###
GET http://localhost:3000/api/carrera/
###
POST http://localhost:3000/api/carrera
Content-Type: application/json

{
  "nombre": "Gran Premio de Australia",
  "fecha_carrera": "2025-03-23",
  "hora_carrera": 15,
  "circuito": 3
}

###
POST http://localhost:3000/api/carrera
Content-Type: application/json

{
  "nombre": "Gran Premio de Bahréin",
  "fecha_carrera": "2025-03-30",
  "hora_carrera": 17,

  "circuito": 1
}

###
POST http://localhost:3000/api/carrera
Content-Type: application/json

{
  "nombre": "Gran Premio de China",
  "fecha_carrera": "2025-04-13",
  "hora_carrera": 14,
  "vuelta_rapida": null,
  "pole": null,
  "circuito": 2
}

###
POST http://localhost:3000/api/carrera
Content-Type: application/json

{
  "nombre": "Gran Premio de Gran Bretaña",
  "fecha_carrera": "2025-07-06",
  "hora_carrera": 15,
  "circuito": 3
}

###
POST http://localhost:3000/api/carrera
Content-Type: application/json

{
  "nombre": "Gran Premio de Hungría",
  "fecha_carrera": "2025-07-20",
  "hora_carrera": 15,
  "circuito": 1
}
