
### Rest Client Extension
GET http://localhost:3000/api/piloto/

###
GET http://localhost:3000/api/piloto/activo

###
# @name createpiloto
POST http://localhost:3000/api/piloto
Content-Type: application/json

{
  "nombre": "Carlos",
  "apellido": "Sainz",
  "nacionalidad": "España",
  "numero": 55,
  "fecha_nacimiento": "1994-09-01",
  "estado": "Activo",
  "debut": "2015",
  "titulos": 0,
  "escuderia": 1
}

### ID
@id = {{createpiloto.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/piloto/{{id}}




###
PUT http://localhost:3000/api/piloto/{{id}}
Content-Type: application/json

{
    "nombre": "Mercedes-AMG Petronas Formula One Team",
    "pais_base": "Reino Unido",
    "jefe_equipo": "Toto Wolff",
    "motor": "Mercedes"
}

###
PATCH http://localhost:3000/api/piloto/3
Content-Type: application/json

{
    "nombre": "Oracle Red Bull Racing",
    "pais_base": "Reino Unido",
    "jefe_equipo": "Christian Horner",
    "motor": "Red Bull Powertrains"
}

###
DELETE http://localhost:3000/api/piloto/{{id}}

POST http://localhost:3000/api/piloto
Content-Type: application/json

{
  "nombre": "Max",
  "apellido": "Verstappen",
  "nacionalidad": "Países Bajos",
  "numero": 1,
  "fecha_nacimiento": "1997-09-30",
  "estado": "activo",
  "debut": "2015",
  "titulos": 3,
  "escuderia": 2
}
###
POST http://localhost:3000/api/piloto
Content-Type: application/json

{
  "nombre": "Lewis",
  "apellido": "Hamilton",
  "nacionalidad": "Reino Unido",
  "numero": 44,
  "fecha_nacimiento": "1985-01-07",
  "estado": "activo",
  "debut": "2007",
  "titulos": 7,
  "escuderia": 3
}
###
POST http://localhost:3000/api/piloto
Content-Type: application/json

{
  "nombre": "Sebastian",
  "apellido": "Vettel",
  "nacionalidad": "Alemania",
  "numero": 5,
  "fecha_nacimiento": "1987-07-03",
  "estado": "retirado",
  "debut": "2007",
  "titulos": 4,
  "escuderia": 1
}
###
POST http://localhost:3000/api/piloto
Content-Type: application/json

{
  "nombre": "Fernando",
  "apellido": "Alonso",
  "nacionalidad": "España",
  "numero": 14,
  "fecha_nacimiento": "1981-07-29",
  "estado": "activo",
  "debut": "2001",
  "titulos": 2,
  "escuderia": 5
}
###
POST http://localhost:3000/api/piloto
Content-Type: application/json

{
  "nombre": "Charles",
  "apellido": "Leclerc",
  "nacionalidad": "Mónaco",
  "numero": 16,
  "fecha_nacimiento": "1997-10-16",
  "estado": "activo",
  "debut": "2018",
  "titulos": 0,
  "escuderia": 1
}

###
# @name createpiloto
POST http://localhost:3000/api/piloto
Content-Type: application/json

{
  "nombre": "Franco",
  "apellido": "Colapinto",
  "nacionalidad": "Argentina",
  "numero": 43,
  "fecha_nacimiento": "2003-05-27",
  "estado": "activo",
  "debut": "2024",
  "titulos": 0,
  "escuderia": 1
}


