
### Rest Client Extension
GET http://localhost:3000/api/escuderia/5

###
# @name createEscuderia
POST http://localhost:3000/api/escuderia
Content-Type: application/json

{   
    "nombre": "Scuderia Skywalker Reicing",
    "pais_base": "Italia",
    "debut": "Premio Argentina 1950",
    "jefe_equipo": "Luke Skywalker",
    "motor": "Ferrari",
    "auto_img": "",
    "logo": ""
}
###
PATCH http://localhost:3000/api/escuderia/5
Content-Type: application/json

{   
    "nombre": "Scuderia Skywalker Reicing",
    "pais_base": "Italia",
    "debut": "Gran Premio Argentina 1950",
    "jefe_equipo": "Luke Skywalker",
    "motor": "Ferrari",
    "auto_img": "",
    "logo": ""
}
###
DELETE http://localhost:3000/api/escuderia/5

### ID
@id = {{createEscuderia.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/escuderia/{{id}}




###
PUT http://localhost:3000/api/escuderia/{{id}}
Content-Type: application/json

{
    "nombre": "Mercedes-AMG Petronas Formula One Team",
    "pais_base": "Reino Unido",
    "jefe_equipo": "Toto Wolff",
    "motor": "Mercedes"
}

###
PATCH http://localhost:3000/api/escuderia/3
Content-Type: application/json

{
    "nombre": "Oracle Red Bull Racing",
    "pais_base": "Reino Unido",
    "jefe_equipo": "Christian Horner",
    "motor": "Red Bull Powertrains"
}

###
DELETE http://localhost:3000/api/escuderia/{{id}}