
### Rest Client Extension
GET http://localhost:3000/api/usuario/

###
# @name createEscuderia
POST http://localhost:3000/api/usuario/
Content-Type: application/json

{
  "nombre_usuario": "administrador",
  "nombre": "Pedro",
  "apellido": "Moretti Yrure",
  "email": "pedro@example.com",
  "password": "123456",  
  "pais": "Argentina",
  "user_img": null,
  "rol": "admin"
}

### Crear Admin Inicial
POST http://localhost:3000/api/usuario/
Content-Type: application/json

{
  "nombre_usuario": "bruno",
  "nombre": "Bruno",
  "apellido": "Bernard",
  "email": "bruno@example.com",
  "password": "admin123",  
  "pais": "Argentina",
  "user_img": null,
  "rol": "admin"
}

### ID
@id = {{createEscuderia.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/usuario/{{id}}




###
PUT http://localhost:3000/api/usuario/{{id}}
Content-Type: application/json

{
    "piloto_fav": 1
}

###
PATCH http://localhost:3000/api/usuario/1
Content-Type: application/json

{
    "piloto_fav": 1
}

###
DELETE http://localhost:3000/api/usuario/{{id}}

###
POST http://localhost:3000/api/usuario/login
Content-Type: application/json

{
  "nombre_usuario": "administrador",
  "password": "123456"
}

###
POST http://localhost:3000/api/usuario/login
Content-Type: application/json

{
  "nombre_usuario": "bruno",
  "password": "admin123"
}